services:
#    sbs_adminlte.example:
#        class: SbS\AdminLTEBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sbs_adminlte.user_listener:
        class: SbS\AdminLTEBundle\EventListener\UserEventListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: sbs.admin_lte.user, method: getUser }

#twig extensions
    sbs_adminlte.twig.user_extension:
        class: SbS\AdminLTEBundle\Twig\UserExtension
        arguments: ["@sbs_adminlte.user_listener"]
        tags:
            - { name: twig.extension }
